// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestTugas
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WpfControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethodPenjumlahan
        /// </summary>
        public void RecordedMethodPenjumlahan()
        {
            #region Variable Declarations
            WpfTitleBar uIMyCalculatorv1TitleBar = this.UIMyCalculatorv1Window.UIMyCalculatorv1TitleBar;
            WpfButton uIDelButton = this.UIMyCalculatorv1Window.UIDelButton;
            WpfButton uIItem7Button = this.UIMyCalculatorv1Window.UIItem7Button;
            WpfButton uIItemButton = this.UIMyCalculatorv1Window.UIItemButton;
            WpfButton uIItem2Button = this.UIMyCalculatorv1Window.UIItem2Button;
            WpfButton uIItemButton1 = this.UIMyCalculatorv1Window.UIItemButton1;
            #endregion

            // Click 'MyCalculator v1' title bar
            Mouse.Click(uIMyCalculatorv1TitleBar, new Point(46, 7));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(23, 19));

            // Click '7' button
            Mouse.Click(uIItem7Button, new Point(18, 9));

            // Click '+' button
            Mouse.Click(uIItemButton, new Point(22, 8));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(24, 18));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(28, 14));
        }
        
        /// <summary>
        /// RecordedMethodPengurangan
        /// </summary>
        public void RecordedMethodPengurangan()
        {
            #region Variable Declarations
            WpfButton uIDelButton = this.UIMyCalculatorv1Window.UIDelButton;
            WpfButton uIItem4Button = this.UIMyCalculatorv1Window.UIItem4Button;
            WpfButton uIItemButton2 = this.UIMyCalculatorv1Window.UIItemButton2;
            WpfButton uIItem2Button = this.UIMyCalculatorv1Window.UIItem2Button;
            WpfButton uIItemButton1 = this.UIMyCalculatorv1Window.UIItemButton1;
            #endregion

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(38, 13));

            // Click '4' button
            Mouse.Click(uIItem4Button, new Point(25, 19));

            // Click '-' button
            Mouse.Click(uIItemButton2, new Point(13, 12));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(31, 21));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(47, 17));
        }
        
        /// <summary>
        /// RecordedMethodPerkalian
        /// </summary>
        public void RecordedMethodPerkalian()
        {
            #region Variable Declarations
            WpfButton uIDelButton = this.UIMyCalculatorv1Window.UIDelButton;
            WpfButton uIItem4Button = this.UIMyCalculatorv1Window.UIItem4Button;
            WpfButton uIItemButton3 = this.UIMyCalculatorv1Window.UIItemButton3;
            WpfButton uIItemButton1 = this.UIMyCalculatorv1Window.UIItemButton1;
            #endregion

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(36, 9));

            // Click '4' button
            Mouse.Click(uIItem4Button, new Point(24, 24));

            // Click '*' button
            Mouse.Click(uIItemButton3, new Point(7, 30));

            // Click '4' button
            Mouse.Click(uIItem4Button, new Point(28, 20));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(19, 16));
        }
        
        /// <summary>
        /// RecordedMethodPembagian
        /// </summary>
        public void RecordedMethodPembagian()
        {
            #region Variable Declarations
            WpfButton uIItem9Button = this.UIMyCalculatorv1Window.UIItem9Button;
            WpfButton uIDelButton = this.UIMyCalculatorv1Window.UIDelButton;
            WpfButton uIItemButton4 = this.UIMyCalculatorv1Window.UIItemButton4;
            WpfButton uIItem3Button = this.UIMyCalculatorv1Window.UIItem3Button;
            WpfButton uIItemButton1 = this.UIMyCalculatorv1Window.UIItemButton1;
            #endregion

            // Click '9' button
            Mouse.Click(uIItem9Button, new Point(19, 20));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(27, 13));

            // Click '9' button
            Mouse.Click(uIItem9Button, new Point(29, 20));

            // Click '/' button
            Mouse.Click(uIItemButton4, new Point(30, 19));

            // Click '3' button
            Mouse.Click(uIItem3Button, new Point(17, 10));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(51, 8));
        }
        
        /// <summary>
        /// RecordedMethod1
        /// </summary>
        public void RecordedMethod1()
        {
            #region Variable Declarations
            WpfButton uIItem5Button = this.UIMyCalculatorv1Window.UIItem5Button;
            WpfButton uIDelButton = this.UIMyCalculatorv1Window.UIDelButton;
            #endregion

            // Click '5' button
            Mouse.Click(uIItem5Button, new Point(32, 19));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(19, 26));
        }
        
        /// <summary>
        /// RecordedMethodDelete
        /// </summary>
        public void RecordedMethodDelete()
        {
            #region Variable Declarations
            WpfButton uIItem8Button = this.UIMyCalculatorv1Window.UIItem8Button;
            WpfButton uIDelButton = this.UIMyCalculatorv1Window.UIDelButton;
            #endregion

            // Click '8' button
            Mouse.Click(uIItem8Button, new Point(32, 23));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(28, 16));
        }
        
        /// <summary>
        /// RecordedMethodR
        /// </summary>
        public void RecordedMethodR()
        {
            #region Variable Declarations
            WpfButton uIItem1Button = this.UIMyCalculatorv1Window.UIItem1Button;
            WpfButton uIItem2Button = this.UIMyCalculatorv1Window.UIItem2Button;
            WpfButton uIItem4Button = this.UIMyCalculatorv1Window.UIItem4Button;
            WpfButton uIRButton = this.UIMyCalculatorv1Window.UIRButton;
            #endregion

            // Click '1' button
            Mouse.Click(uIItem1Button, new Point(23, 12));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(33, 11));

            // Click '4' button
            Mouse.Click(uIItem4Button, new Point(30, 18));

            // Click 'R' button
            Mouse.Click(uIRButton, new Point(22, 13));
        }
        
        /// <summary>
        /// Recordedpenjumlahan2
        /// </summary>
        public void Recordedpenjumlahan2()
        {
            #region Variable Declarations
            WpfButton uIItem1Button = this.UIMyCalculatorv1Window.UIItem1Button;
            WpfButton uIDelButton = this.UIMyCalculatorv1Window.UIDelButton;
            WpfButton uIItem7Button = this.UIMyCalculatorv1Window.UIItem7Button;
            WpfButton uIItemButton3 = this.UIMyCalculatorv1Window.UIItemButton3;
            WpfButton uIItem4Button = this.UIMyCalculatorv1Window.UIItem4Button;
            WpfButton uIItemButton4 = this.UIMyCalculatorv1Window.UIItemButton4;
            WpfButton uIItem2Button = this.UIMyCalculatorv1Window.UIItem2Button;
            WpfButton uIItemButton1 = this.UIMyCalculatorv1Window.UIItemButton1;
            WpfButton uIItemButton2 = this.UIMyCalculatorv1Window.UIItemButton2;
            WpfButton uIItem3Button = this.UIMyCalculatorv1Window.UIItem3Button;
            WpfButton uIItemButton = this.UIMyCalculatorv1Window.UIItemButton;
            #endregion

            // Click '1' button
            Mouse.Click(uIItem1Button, new Point(35, 25));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(30, 18));

            // Click '7' button
            Mouse.Click(uIItem7Button, new Point(30, 14));

            // Click '*' button
            Mouse.Click(uIItemButton3, new Point(12, 11));

            // Click '4' button
            Mouse.Click(uIItem4Button, new Point(15, 12));

            // Click '/' button
            Mouse.Click(uIItemButton4, new Point(19, 13));

            // Click '2' button
            Mouse.Click(uIItem2Button, new Point(24, 14));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(67, 10));

            // Click 'Del' button
            Mouse.Click(uIDelButton, new Point(29, 18));

            // Move '-' button to '3' button
            uIItem3Button.EnsureClickable(new Point(28, 14));
            Mouse.StartDragging(uIItemButton2, new Point(3, 18));
            Mouse.StopDragging(uIItem3Button, new Point(28, 14));

            // Click '3' button
            Mouse.Click(uIItem3Button, new Point(28, 15));

            // Click '+' button
            Mouse.Click(uIItemButton, new Point(24, 9));

            // Click '3' button
            Mouse.Click(uIItem3Button, new Point(23, 12));

            // Click '-' button
            Mouse.Click(uIItemButton2, new Point(1, 7));

            // Click '1' button
            Mouse.Click(uIItem1Button, new Point(30, 6));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(28, 16));
        }
        
        /// <summary>
        /// RecordedMethodDivineZero
        /// </summary>
        public void RecordedMethodDivineZero()
        {
            #region Variable Declarations
            WpfButton uIItem9Button = this.UIMyCalculatorv1Window.UIItem9Button;
            WpfButton uIItemButton4 = this.UIMyCalculatorv1Window.UIItemButton4;
            WpfButton uIItem0Button = this.UIMyCalculatorv1Window.UIItem0Button;
            WpfButton uIItemButton1 = this.UIMyCalculatorv1Window.UIItemButton1;
            #endregion

            // Click '9' button
            Mouse.Click(uIItem9Button, new Point(25, 24));

            // Click '/' button
            Mouse.Click(uIItemButton4, new Point(31, 15));

            // Click '0' button
            Mouse.Click(uIItem0Button, new Point(6, 23));

            // Click '=' button
            Mouse.Click(uIItemButton1, new Point(51, 9));
        }
        
        #region Properties
        public UIMyCalculatorv1Window UIMyCalculatorv1Window
        {
            get
            {
                if ((this.mUIMyCalculatorv1Window == null))
                {
                    this.mUIMyCalculatorv1Window = new UIMyCalculatorv1Window();
                }
                return this.mUIMyCalculatorv1Window;
            }
        }
        #endregion
        
        #region Fields
        private UIMyCalculatorv1Window mUIMyCalculatorv1Window;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIMyCalculatorv1Window : WpfWindow
    {
        
        public UIMyCalculatorv1Window()
        {
            #region Search Criteria
            this.SearchProperties[WpfWindow.PropertyNames.Name] = "MyCalculator v1";
            this.SearchProperties.Add(new PropertyExpression(WpfWindow.PropertyNames.ClassName, "HwndWrapper", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("MyCalculator v1");
            #endregion
        }
        
        #region Properties
        public WpfTitleBar UIMyCalculatorv1TitleBar
        {
            get
            {
                if ((this.mUIMyCalculatorv1TitleBar == null))
                {
                    this.mUIMyCalculatorv1TitleBar = new WpfTitleBar(this);
                    #region Search Criteria
                    this.mUIMyCalculatorv1TitleBar.SearchProperties[WpfTitleBar.PropertyNames.AutomationId] = "TitleBar";
                    this.mUIMyCalculatorv1TitleBar.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIMyCalculatorv1TitleBar;
            }
        }
        
        public WpfButton UIDelButton
        {
            get
            {
                if ((this.mUIDelButton == null))
                {
                    this.mUIDelButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIDelButton.SearchProperties[WpfButton.PropertyNames.Name] = "Del";
                    this.mUIDelButton.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIDelButton;
            }
        }
        
        public WpfButton UIItem7Button
        {
            get
            {
                if ((this.mUIItem7Button == null))
                {
                    this.mUIItem7Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem7Button.SearchProperties[WpfButton.PropertyNames.Name] = "7";
                    this.mUIItem7Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem7Button;
            }
        }
        
        public WpfButton UIItemButton
        {
            get
            {
                if ((this.mUIItemButton == null))
                {
                    this.mUIItemButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton.SearchProperties[WpfButton.PropertyNames.Name] = "+";
                    this.mUIItemButton.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton;
            }
        }
        
        public WpfButton UIItem2Button
        {
            get
            {
                if ((this.mUIItem2Button == null))
                {
                    this.mUIItem2Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem2Button.SearchProperties[WpfButton.PropertyNames.Name] = "2";
                    this.mUIItem2Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem2Button;
            }
        }
        
        public WpfButton UIItemButton1
        {
            get
            {
                if ((this.mUIItemButton1 == null))
                {
                    this.mUIItemButton1 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton1.SearchProperties[WpfButton.PropertyNames.Name] = "=";
                    this.mUIItemButton1.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton1;
            }
        }
        
        public WpfButton UIItem4Button
        {
            get
            {
                if ((this.mUIItem4Button == null))
                {
                    this.mUIItem4Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem4Button.SearchProperties[WpfButton.PropertyNames.Name] = "4";
                    this.mUIItem4Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem4Button;
            }
        }
        
        public WpfButton UIItemButton2
        {
            get
            {
                if ((this.mUIItemButton2 == null))
                {
                    this.mUIItemButton2 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton2.SearchProperties[WpfButton.PropertyNames.Name] = "-";
                    this.mUIItemButton2.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton2;
            }
        }
        
        public WpfButton UIItemButton3
        {
            get
            {
                if ((this.mUIItemButton3 == null))
                {
                    this.mUIItemButton3 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton3.SearchProperties[WpfButton.PropertyNames.Name] = "*";
                    this.mUIItemButton3.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton3;
            }
        }
        
        public WpfButton UIItem9Button
        {
            get
            {
                if ((this.mUIItem9Button == null))
                {
                    this.mUIItem9Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem9Button.SearchProperties[WpfButton.PropertyNames.Name] = "9";
                    this.mUIItem9Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem9Button;
            }
        }
        
        public WpfButton UIItemButton4
        {
            get
            {
                if ((this.mUIItemButton4 == null))
                {
                    this.mUIItemButton4 = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItemButton4.SearchProperties[WpfButton.PropertyNames.Name] = "/";
                    this.mUIItemButton4.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItemButton4;
            }
        }
        
        public WpfButton UIItem3Button
        {
            get
            {
                if ((this.mUIItem3Button == null))
                {
                    this.mUIItem3Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem3Button.SearchProperties[WpfButton.PropertyNames.Name] = "3";
                    this.mUIItem3Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem3Button;
            }
        }
        
        public WpfButton UIItem5Button
        {
            get
            {
                if ((this.mUIItem5Button == null))
                {
                    this.mUIItem5Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem5Button.SearchProperties[WpfButton.PropertyNames.Name] = "5";
                    this.mUIItem5Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem5Button;
            }
        }
        
        public WpfButton UIItem8Button
        {
            get
            {
                if ((this.mUIItem8Button == null))
                {
                    this.mUIItem8Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem8Button.SearchProperties[WpfButton.PropertyNames.Name] = "8";
                    this.mUIItem8Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem8Button;
            }
        }
        
        public WpfButton UIItem1Button
        {
            get
            {
                if ((this.mUIItem1Button == null))
                {
                    this.mUIItem1Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem1Button.SearchProperties[WpfButton.PropertyNames.Name] = "1";
                    this.mUIItem1Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem1Button;
            }
        }
        
        public WpfButton UIRButton
        {
            get
            {
                if ((this.mUIRButton == null))
                {
                    this.mUIRButton = new WpfButton(this);
                    #region Search Criteria
                    this.mUIRButton.SearchProperties[WpfButton.PropertyNames.Name] = "R";
                    this.mUIRButton.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIRButton;
            }
        }
        
        public WpfButton UIItem0Button
        {
            get
            {
                if ((this.mUIItem0Button == null))
                {
                    this.mUIItem0Button = new WpfButton(this);
                    #region Search Criteria
                    this.mUIItem0Button.SearchProperties[WpfButton.PropertyNames.Name] = "0";
                    this.mUIItem0Button.WindowTitles.Add("MyCalculator v1");
                    #endregion
                }
                return this.mUIItem0Button;
            }
        }
        #endregion
        
        #region Fields
        private WpfTitleBar mUIMyCalculatorv1TitleBar;
        
        private WpfButton mUIDelButton;
        
        private WpfButton mUIItem7Button;
        
        private WpfButton mUIItemButton;
        
        private WpfButton mUIItem2Button;
        
        private WpfButton mUIItemButton1;
        
        private WpfButton mUIItem4Button;
        
        private WpfButton mUIItemButton2;
        
        private WpfButton mUIItemButton3;
        
        private WpfButton mUIItem9Button;
        
        private WpfButton mUIItemButton4;
        
        private WpfButton mUIItem3Button;
        
        private WpfButton mUIItem5Button;
        
        private WpfButton mUIItem8Button;
        
        private WpfButton mUIItem1Button;
        
        private WpfButton mUIRButton;
        
        private WpfButton mUIItem0Button;
        #endregion
    }
}
